name: CI-CD

on: 
  push:
    branches: ["main"]
  workflow_dispatch: 
jobs:
  ci: 
    runs-on: ubuntu-latest
    steps:
      - name: Obter o código do projeto
        uses: actions/checkout@v4
      
      - name: Autenticar no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

          
      - name: Construção da imagem docker
        run: echo "executando o comando docker build"
      - name: Envio da imagem docker
        run: echo "executando o comando docker push"

  cd: 
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - name: autenticar na AWS
        run: echo "executando o comando aws configure"
      - name: Configurar o kubclt
        run: echo "executando o comando aws eks update-kubeconfig"
      - name: Aplicar os manifestos no kubernetes
        run: echo "executando o comando kubectl apply"
    
    

      
        
